### ISSUE TITLE
Bug Report | Proxied media issues

### ISSUE THREAD

**Issue by spikecodes** [spikecodes/libreddit#147]
## Describe the bug
Libreddit proxies videos synchronously. This causes videos on some devices to buffer for a long time (while Libreddit downloads the videos to the stack) and makes videos on other devices (such as iOS and MacOS devices) no longer compliant with the playback formats.

### ~~1. [Video playback is slow in Vivaldi](https://github.com/spikecodes/libreddit/issues/145)~~
I assume this issue happens in other browsers as well, though I've only tested this issue in Firefox, Vivaldi and Brave. Each rendering engine handles media differently. The video buffers for a long time (I measured 30 seconds for one video) before playing.

### 2. [Video playback is broken in WebKit-based browsers](https://github.com/spikecodes/libreddit/issues/76)
I haven't found this to be an issue in Firefox or Brave but it appears WebKit handles media differently than Gecko and Chromium do. Based on my research, it appears the slashed grey play button shows that the proxied MP4s aren't "compliant" with WebKit video guidelines.

### ~~3. [Videos have no audio](https://github.com/spikecodes/libreddit/issues/14)~~
This is less of a bug and more of a missing feature as Reddit stores the audio and video separately. Below, I proposed different solutions that could "mux" (combine) the audio and video clips before the users play them.
![image](https://user-images.githubusercontent.com/19519553/110815401-4f233980-8282-11eb-9f46-ad6611fed293.png)

---

### :heavy_check_mark: 1. [Stream both Reddit headers and the media body through Tide](https://github.com/http-rs/tide/issues/813)
Currently, Tide supports streaming a Body from a reader but I don't believe the same applies for headers (we will see). This solution would be ideal as it would require the least major changes to the codebase.

### 2. Download the media to the instance's storage for faster fetching
This solution would require quite a lot of storage on the hosted instance which may make it unsuitable for Repl.it (which has a size limit for REPLs). Storing the media would allow the video to be merged with the audio which would fix #14. This is the method used by Teddit for proxied media.

### 3. Stream the request through an alternative HTTP server that supports it

---

### 1. Combine the audio and video server-side
The only video solution that I could see working with this is downloading the entire media offline before muxing and serving them again.

### :heavy_check_mark: 2. [Use JavaScript to combine the Reddit-proxied audio and video client side](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Live_streaming_web_audio_and_video#hls)
Ideally, Libreddit would work entirely without JavaScript but if the other solutions are not possible, then it may be required. Reddit serves a HLS url for posts which is likely what Libreddit would use in this scenario. This approach is also taken by [Nitter](https://github.com/zedeus/nitter).

The HLS url stream can be parsed from Reddit's API:
```rust
post["data"]["secure_media"]["reddit_video"]["hls_url"]
```

---

## Additional context
I have concluded that #145, #76, and #14 all stem from the method Libreddit uses to proxy content so I have unified these issues under a single bug report.

**Comment by TheCultLeader666** [comment]
I managed to catch all the Vivaldi issues all in one clip

https://user-images.githubusercontent.com/65368815/110854041-5e09ec00-8282-11eb-90fa-3a826e87768e.mov

**Comment by Codemonkey51** [comment]
Could you use something like this: https://stackoverflow.com/a/32323192/15264500 to fix the videos not having audio problem without having to combine the video and audio server side.

**Comment by spikecodes** [comment]
Thanks Codemonkey! I've added client-side muxing as a possible audio solution to the issue.

**Comment by Codemonkey51** [comment]
> Thanks Codemonkey! I've added client-side muxing as a possible audio solution to the issue.

Your welcome! :D

**Comment by Codemonkey51** [comment]
> Ideally, Libreddit would work entirely without JavaScript but if the other solutions are not possible, then it may be required.

Maybe for this solution, it could be an optional setting. So people who don't want js running can have it disabled, but people who are fine with it can enable it.

**Comment by TheCultLeader666** [comment]
I second this, that's how they do it in nitter

**Comment by TheCultLeader666** [comment]
OK, all videos now appear to be only 4-5 seconds long at most, and just cut off after that point.

**Comment by spikecodes** [comment]
I've been working on a rewrite of Libreddit using [Hyper](https://github.com/hyperium/hyper) that handles asynchronous code and asynchronous proxying much better than v0.4.x did. From my testing, I have found that this rewrite fixed every issue with Vivaldi and Chromium that I had been having before (this one actually streams proxied media asynchronously). I am near certain that the Safari and WebKit issues would be fixed by this rewrite as well.

**Comment by TheCultLeader666** [comment]
Amazing!

**Comment by spikecodes** [comment]
Thank you! :) I appreciate everyone's patience as well. This v0.5 rewrite will use almost half the crates that v0.4 did and will compile and run much faster.

**Comment by TheCultLeader666** [comment]
In my experience it is already very lightweight, being able to run perfectly under docker on my 2015 macbook air, along with Vivaldi and many other apps, Vivaldi being one of the most intensive browsers out there in terms of resources, so It's awesome that you're able to make it much faster than it already is, which is _pretty darn fast!_

**Comment by spikecodes** [comment]
I just pushed [the rewrite](https://github.com/spikecodes/libreddit/commit/b14b4ff551f24eec08bf7647c88dcea85b6a0d73)! Before I deploy the next release, let me know if the video playback issues clear up in Safari and Vivaldi on [the main instance](https://libredd.it) which is running v0.5.

**Comment by TheCultLeader666** [comment]
Ok. The lack of audio and webkit issues are still present on libredd.it, but the Vivaldi issue seems to have gotten much better!

**Comment by spikecodes** [comment]
Yeah this rewrite doesn't tackle audio, it should fix video though. Which issues in WebKit-based browsers do you have? Does the video play or show a grey slashed play button?

**Comment by TheCultLeader666** [comment]
Yeah, that's the issue, reproduced on both iOS firefox and Safari on both iOS and macOS

**Comment by spikecodes** [comment]
Darn, I have no idea then. The rewrite streams the video asynchronously so it should be scrubbable (which it wasn't in Vivaldi previously) and it sounded like both issues between Vivaldi and WebKit stemmed from the synchronous proxying that Libreddit used before. Which Vivaldi issues still persist?

**Comment by TheCultLeader666** [comment]
The weird aspect ratio thing, bit but that's negligible. And now I can press play on minutes long videos and it will play almost instantly, while before it wouldn't even register it as that length

**Comment by TheCultLeader666** [comment]
This is so much better on so many levels

**Comment by spikecodes** [comment]
Wonderful! I'm going to keep this issue open for the audio and WebKit issues but will be publishing this rewrite shortly, once I finish a bit more testing.

**Comment by TheCultLeader666** [comment]
Lmao I'm currently watching the live docker check in anticipation

**Comment by TheCultLeader666** [comment]
Is v5.0 on the docker hub yet? Just updated and still seems to be the old version

**Comment by spikecodes** [comment]
I just tried re-pulling Libreddit from Docker and it says the version tagged `latest` is v0.5 so yeah it should be on Docker Hub now.

**Comment by TheCultLeader666** [comment]
Yeah, I'm pretty sure that the command listed in the docker install instructions only pulls if there isn't already an image, so you might want to add the pull command for it. I'll open a PR while I'm thinking about it

**Comment by Mennaruuk** [comment]
Something interesting I found. So I have this iOS Shortcut (think of it like an extension) called [Safari Download Video](https://www.icloud.com/shortcuts/61a7ab9d7b11411bbfcbcb1a9d77144f). When I went to any Reddit video and turned on this shortcut, it fetched the video directly, and I was able to play it. Seems like while the video is unplayable in the player, once it’s fetched directly, it plays just fine. Just food for thought.

https://user-images.githubusercontent.com/52135169/111580433-e3fbca80-878d-11eb-9fbb-660a190901db.mp4

**Comment by TheCultLeader666** [comment]
I used the desktop developer tools and managed to get this error when opening the videos in a new tab: `Failed to load resource: Plug-in handled load`

**Comment by TheCultLeader666** [comment]
Thought I'd put this here, as it is as good of a place as any, but it'd be cool if you could set up your github profile to accept 
Brave BAT tips. :)

**Comment by Mennaruuk** [comment]
I think that'd be a wonderful idea! Maybe even set up GitHub Sponsors, it's a nice little widget on the right of the screen that shows ways to support this great project :)

**Comment by OpenWick** [comment]
So Right now is there a way to watch videos with audio without leaving libreddit? Any alternative?

**Comment by TheCultLeader666** [comment]
No not really

**Comment by OpenWick** [comment]
I see there is a PR which is trying to fix this issue. Any reason why it isn't merged yet? 
I also found Teddit also implemented similar hls media playback.
But I find libreddit much easier to use on mobile than teddit.
So any idea when the PR be merged?

**Comment by spikecodes** [comment]
I've commented on the PR and am currently pending a response from the maintainer

**Comment by spikecodes** [comment]
Videos now have audio in [v0.12.0](https://github.com/spikecodes/libreddit/releases/tag/v0.12.0) thanks to #182!

**Comment by spikecodes** [comment]
Now that Libreddit has switched to HLS for video playback, I feel comfortable closing this issue but let me know if any problem listed here persists and I'll reopen it.

**Comment by phil294** [comment]
Is HLS possible without the use of JavaScript? Video Audio is the only thing consistently not working with no js.
