### ISSUE TITLE
Incorrect "No video with supported format and MIME type found"

### ISSUE THREAD

**Issue by wizard-28** [spikecodes/libreddit#322]
## Describe the bug

After I enabled auto-play some videos are unable to play while I scroll down the webpage. This error is shown
![error](https://0x0.st/-RYk.png)

But when I click the post's title and go to the page the video starts playing fine.
![video-playing](https://0x0.st/-RY7.png)

## To reproduce

1. Enable auto-play in settings
2. See that some videos are unable to play

## Expected behavior

The video plays normally.

## Additional context

1. I'm on LibreWolf 94 ( based on Firefox 94 ), and using https://libreddit.spike.codes instance v0.17.0.
2. Also this issue doesn't occur for all videos. Some videos play fine automatically with auto-play enabled.
3. Some errors are printed on the console
![errors-console](https://0x0.st/-Rgr.png)

**Comment by mikupls** [comment]
Trying to reproduce, I used http://libredd.it/r/HolUp/search?q=uhhh&restrict_sr=on, but the video plays for me.

Could this issue be related to LibreWolf? I have never heard about that Browser before. Could you try a different browser to reproduce the issue?

**Comment by spikecodes** [comment]
I think I have noticed the issue before but am unable to reproduce it. Are you able to share a link to a post where you experienced this? @wizard-28

**Comment by wizard-28** [comment]
> I think I have noticed the issue before but am unable to reproduce it. Are you able to share a link to a post where you experienced this? @wizard-28

Working correctly in:
1. https://libreddit.kavin.rocks/r/memes/comments/qz4eq1/starting_from_scratch/
2. https://libreddit.kavin.rocks/r/memes/comments/qz6l0n/wait_surely_you_didnt_actually_believe_me_you/

Experiencing issues in:
1.https://libreddit.kavin.rocks/r/Vanced/comments/qyr6gn/question_comments_disappear_after_20_seconds_how/
2. https://libreddit.kavin.rocks/r/commandline/comments/qyhny3/anktui_add_notes_to_anki_from_the_terminal/
3. https://libreddit.kavin.rocks/r/HolUp/comments/qzaiau/nice_nice/
4. https://libreddit.kavin.rocks/r/HolUp/comments/qz1pjc/%CA%95_%C2%BA_%E1%B4%A5_%C2%BA%CA%94/

**Comment by wizard-28** [comment]
> Trying to reproduce, I used http://libredd.it/r/HolUp/search?q=uhhh&restrict_sr=on, but the video plays for me.
> 
> Could this issue be related to LibreWolf? I have never heard about that Browser before. Could you try a different browser to reproduce the issue?

Opened that link in mainline Firefox, with auto-play enabled. Got the same issue.

---

On a side note, turning on "autoplay" in settings doesn't actually ask to enable the site permission. I have to manually go to site settings and enable it in Firefox based browsers. I couldn't find the same settings for chromium based ones, so I couldn't really test it there.

**Comment by spikecodes** [comment]
I was able to reproduce with HLS enabled at https://r.nf/r/HolUp/search?q=uhhh&restrict_sr=on in Firefox 94, Libreddit v018.1

**Comment by mikupls** [comment]
Ah, good to know wizard-28; I thought autoplay was broken for me, but enabling it explicitly in Firefox's settings made it work.

If I understand correctly that you only sometimes get this error for the same video, and it only starts happening once auto-play is on, I believe that an easy explanation could be network problems. If the connection is too slow/overloaded (possibly due to autoplay), it will fail fetching some video data, which AFAIK can result in such an error message.

I also get the error message about the "type" attribute btw (from comment#1).

**Comment by spikecodes** [comment]
[Fixed](https://github.com/spikecodes/libreddit/commit/923ff776bd5e88245dd8c39e55fa82594a3817cb)! The issue only happened when HLS is enabled so I thought what happened was:
1. HTML defines src of `<video>` to be `about:blank` (placeholder before JS begins streaming)
2. Video is played automatically with autoplay enabled
3. Firefox fetches `about:blank` and fails to parse that into a video
4. HLS.js streams the .m3u file into it but Firefox fails to switch video sources

Instead, I've removed the HTML that told the browser to autoplay the video and told the JS file (when the preference is enabled) to autoplay.

**Comment by DUOLabs333** [comment]
I still have this issue when compiling from git with `cargo build --release --locked --all-features`. Firefox 88.

**Comment by DUOLabs333** [comment]
Never mind, it only happens when I enable the Firefox extension, "Disable Autoplay".
